coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
    - "src/main/java/il/ac/technion/cs/smarthouse/applications/*"
    - "src/main/java/il/ac/technion/cs/smarthouse/sensors/sos/gui/*"
    - "src/main/java/il/ac/technion/cs/smarthouse/sensors/stove/gui/*"
    - "src/main/java/il/ac/technion/cs/smarthouse/sensors/vitals/gui/*"
    - "src/main/java/il/ac/technion/cs/smarthouse/system/gui/*"
