coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
    - "Smarthouse/system/src/main/java/il/ac/technion/cs/smarthouse/applications/*"
    - "Smarthouse/sensors/src/main/java/il/ac/technion/cs/smarthouse/sensors/sos/gui/*"
    - "Smarthouse/sensors/src/main/java/il/ac/technion/cs/smarthouse/sensors/stove/gui/*"
    - "Smarthouse/sensors/src/main/java/il/ac/technion/cs/smarthouse/sensors/vitals/gui/*"
    - "Smarthouse/system_gui/*"
