language: java
jdk: oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

# safe list: add here branches you want to verify the build & tests will pass
branches:
 only:
  - master

before_install:
 - pip install --user codecov    #Install codecov

# add this if you use maven for your project and want to verify mvn build is successful and all unit tests pass.
script:
 #- mvn test
 #- mvn cobertura:cobertura


# running coverage tool
after_success:
- codecov
#- bash <(curl -s https://codecov.io/bash)
